-- Creacion de reporte
-- Reporte sobre la cantidad de clientes por año.
SELECT
	EXTRACT(YEAR FROM AGENTE_VENDEDOR.FECH_CONTR) AS FECHA,
	COUNT(CLIENTE.ID_CLIEN) AS NUMERO_CLIENTES
FROM REGISTRO
	INNER JOIN CLIENTE ON REGISTRO.ID_CLIEN = CLIENTE.ID_CLIEN
	INNER JOIN AGENTE_VENDEDOR ON REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT
WHERE REGISTRO.ID_CLIEN = CLIENTE.ID_CLIEN
GROUP BY
	AGENTE_VENDEDOR.FECH_CONTR
ORDER BY AGENTE_VENDEDOR.FECH_CONTR ASC;