-- Creacion de trigger
/* Trigger capaz de hacer que el costo de pago del agente vendedor tenga un bono del 10%
   cuando el numero de ventas realizadas sea mayor a 10.*/
CREATE OR REPLACE FUNCTION BONO() RETURNS TRIGGER
AS 
	$BONO$
DECLARE
	AUMENTO INT;
BEGIN
	SELECT
		COUNT(REGISTRO.ID_AGENT) INTO AUMENTO
	FROM REGISTRO
		INNER JOIN AGENTE_VENDEDOR ON REGISTRO.ID_AGENT = AGENTE_VENDEDOR.ID_AGENT
	WHERE REGISTRO.ID_AGENT = NEW.ID_AGENT;
	
	IF(AUMENTO < 10) THEN
		RAISE NOTICE 'Aumento no realizado';
	ELSE
		UPDATE AGENTE_VENDEDOR SET PAGO_AGENT = PAGO_AGENT + (PAGO_AGENT * 0.10) WHERE ID_AGENT = NEW.ID_AGENT;
		RAISE NOTICE 'Aumento Realizado';
	END IF;
	RETURN NEW;
END;
$BONO$
LANGUAGE plpgsql;

CREATE TRIGGER BONO AFTER
INSERT ON REGISTRO FOR EACH ROW
EXECUTE PROCEDURE BONO();

INSERT INTO REGISTRO VALUES( 26, 3, 2, 2, 26, null, '1981-10-25', 'Bueno', 'Ninguna', '2021-12-10', '0954126584');

--DELETE FROM REGISTRO WHERE ID_REG = 26
--select * from registro
